link = { dest ~ ("|" ~ alias)? }
dest = { note ~ anchor? }
anchor = { (header | blockref) }

note = { ident }
alias = { ident_extended }
header = { "#" ~ !"^" ~ ident }
blockref = { "#^" ~ ident }

ident = _{ (LETTER | NUMBER | DASH_PUNCTUATION | CONNECTOR_PUNCTUATION | "$" | "(" | ")" )+ }
ident_extended = _{ (!("[[" | "]]" | CONTROL | LINE_SEPARATOR | PARAGRAPH_SEPARATOR ) ~ ANY)+ }
WHITESPACE = _{ " " }
